CREATE TABLE `shop_customers` (
  `id` int(11) NOT NULL auto_increment,
  `first_name` varchar(100) default NULL,
  `last_name` varchar(100) default NULL,
  `email` varchar(50) default NULL,
  `company` varchar(100) default NULL,
  `phone` varchar(100) default NULL,
  `password` varchar(50) default NULL,
  `shipping_street_addr` varchar(255) default NULL,
  `shipping_city` varchar(100) default NULL,
  `shipping_state_id` int default NULL,
  `shipping_zip` varchar(20) default NULL,
  `shipping_country_id` int default NULL,
  `billing_street_addr` varchar(255) default NULL,
  `billing_city` varchar(100) default NULL,
  `billing_state_id` int default NULL,
  `billing_zip` varchar(20) default NULL,
  `billing_country_id` int default NULL,
  `created_user_id` int(11) default NULL,
  `updated_user_id` int(11) default NULL,
  `created_at` datetime default NULL,
  `updated_at` datetime default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8