CREATE TABLE `shop_orders` (
  `id` int(11) NOT NULL auto_increment,
  `order_datetime` datetime default NULL,
  `shipping_method_id` int(11) default NULL,
  `shipping_quote` decimal(15,2) default NULL,
  `shipping_tax` decimal(15,2) default NULL,
  `customer_id` int(11) default NULL,
  `payment_method_id` int(11) default NULL,
  `goods_tax` decimal(15,2) default NULL,
  `billing_first_name` varchar(100) default NULL,
  `billing_last_name` varchar(100) default NULL,
  `billing_email` varchar(50) default NULL,
  `billing_phone` varchar(100) default NULL,
  `billing_company` varchar(100) default NULL,
  `billing_street_addr` varchar(255) default NULL,
  `billing_city` varchar(100) default NULL,
  `billing_state_id` int(11) default NULL,
  `billing_zip` varchar(20) default NULL,
  `billing_country_id` int(11) default NULL,
  `shipping_first_name` varchar(100) default NULL,
  `shipping_last_name` varchar(100) default NULL,
  `shipping_phone` varchar(100) default NULL,
  `shipping_company` varchar(100) default NULL,
  `shipping_street_addr` varchar(255) default NULL,
  `shipping_city` varchar(100) default NULL,
  `shipping_state_id` int(11) default NULL,
  `shipping_zip` varchar(20) default NULL,
  `shipping_country_id` int(11) default NULL,
  PRIMARY KEY  (`id`),
  KEY `billing_last_name` (`billing_last_name`),
  KEY `shipping_last_name` (`shipping_last_name`),
  KEY `billing_email` (`billing_email`),
  KEY `billing_company` (`billing_company`),
  KEY `shipping_company` (`shipping_company`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


